# Generated by Django 5.0.6 on 2024-06-23 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculator_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fx', models.CharField(max_length=200)),
                ('gx', models.CharField(blank=True, max_length=200)),
                ('verify_convergence', models.BooleanField(default=False)),
                ('x0', models.FloatField()),
                ('error', models.FloatField(blank=True, null=True)),
                ('max_iter', models.IntegerField(blank=True, null=True)),
                ('decimals', models.IntegerField(blank=True, null=True)),
                ('h', models.FloatField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
